hmrc/binding-tariff-classification

app/uk/gov/hmrc/bindingtariffclassification/controllers/MicroserviceHelloWorld.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/controllers/MicroserviceHelloWorldControllerSpec.scala
Adding 400 response for testing purpose
=> DIT-193: adding 400 response for testing purpose

app/uk/gov/hmrc/bindingtariffclassification/connector/BankHolidaysConnector.scala, conf/bank-holidays-fallback.json, test/unit/uk/gov/hmrc/bindingtariffclassification/connector/BankHolidaysConnectorTest.scala
This is a temporary fix, really we need a new microservice in the public-internal zone which proxies to the bank-holidays.json file.
=> DIT-693 Add Fallback JSON file

app/uk/gov/hmrc/bindingtariffclassification/model/Attachment.scala, app/uk/gov/hmrc/bindingtariffclassification/model/MongoFormatters.scala, app/uk/gov/hmrc/bindingtariffclassification/model/RESTFormatters.scala, test/it/uk/gov/hmrc/component/CaseSpec.scala, test/util/CaseData.scala
Adding operator on attachments
=> DIT-597  Adding operator on attachments

test/it/uk/gov/hmrc/component/CaseSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepositorySpec.scala
TODO - should search by no trader name return ALL traders?
=> Fix for tests broken by new search by trader name features.

app/uk/gov/hmrc/bindingtariffclassification/controllers/EventController.scala, app/uk/gov/hmrc/bindingtariffclassification/model/Paged.scala, app/uk/gov/hmrc/bindingtariffclassification/model/Search.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepository.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/EventRepository.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/MongoCrudHelper.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/SearchMapper.scala, app/uk/gov/hmrc/bindingtariffclassification/service/CaseService.scala, app/uk/gov/hmrc/bindingtariffclassification/service/EventService.scala, conf/app.routes, test/it/uk/gov/hmrc/bindingtariffclassification/component/CaseSpec.scala, test/it/uk/gov/hmrc/bindingtariffclassification/component/EventSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/controllers/CaseControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/controllers/EventControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/model/PagedTest.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/model/SearchTest.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepositorySpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/EncryptedCaseMongoRepositoryTest.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/EventRepositorySpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/SearchMapperSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/service/CaseServiceSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/service/EventServiceSpec.scala
Done this as a draft until I'm finished with the front end (merging this would break QA at the moment)
=> DIT 805 - Add Pagination to the back end

app/uk/gov/hmrc/bindingtariffclassification/repository/SearchMapper.scala, test/it/uk/gov/hmrc/bindingtariffclassification/component/CaseSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepositorySpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/SearchMapperSpec.scala
If you approve, this can probably be merged as its a non-breaking back end change
=> DIT-876 Filter by SOME assignee/queue

app/uk/gov/hmrc/bindingtariffclassification/service/CaseService.scala
Agreed to change as part of post amigos for DIT-1009 as resulted in a one liner change
=> Use contact name for initial sample status instead of company name

app/uk/gov/hmrc/bindingtariffclassification/model/Event.scala
Related pull requests:
* https://github.com/hmrc/binding-tariff-admin-frontend/pull/62
* https://github.com/hmrc/binding-tariff-data-transformation/pull/42
=> DIT-1987 | Migrating completed liabilities with a new case completed event

app/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepository.scala, app/uk/gov/hmrc/bindingtariffclassification/scheduler/ActiveDaysElapsedJob.scala, conf/application.conf, test/it/uk/gov/hmrc/bindingtariffclassification/component/ActiveDaysElapsedSpec.scala, test/it/uk/gov/hmrc/bindingtariffclassification/component/BaseFeatureSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepositorySpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/EncryptedCaseMongoRepositoryTest.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/scheduler/ActiveDaysElapsedJobTest.scala
Requires DIT-2137 for this to be fully functional.
=> DIT-2233 - Updated activeDaysElapsedJob to handle migrated cases

app/uk/gov/hmrc/bindingtariffclassification/model/CaseFilter.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/SearchMapper.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepositorySpec.scala, test/util/CaseData.scala
Must be merged before https://github.com/hmrc/binding-tariff-trader-frontend/pull/185
=> DIT-2235 Allow filtering by migration status in the case search

app/uk/gov/hmrc/bindingtariffclassification/model/Application.scala
Implements back-end field for https://github.com/hmrc/binding-tariff-trader-frontend/pull/206
=> DIT-2310 - Added sampleIsHazardous field to the application model

app/uk/gov/hmrc/bindingtariffclassification/model/Event.scala, app/uk/gov/hmrc/bindingtariffclassification/model/MongoFormatters.scala, app/uk/gov/hmrc/bindingtariffclassification/model/RESTFormatters.scala
Supporting PR for https://github.com/hmrc/binding-tariff-data-transformation/pull/73
=> DIT-2117 | Added new event type "expert_advice_received"

app/uk/gov/hmrc/bindingtariffclassification/model/Attachment.scala
Supporting PR for https://github.com/hmrc/binding-tariff-data-transformation/pull/82
=> DIT-2121 | Added description to attachment model

app/uk/gov/hmrc/bindingtariffclassification/controllers/CaseController.scala, app/uk/gov/hmrc/bindingtariffclassification/controllers/EventController.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepository.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/EventRepository.scala, app/uk/gov/hmrc/bindingtariffclassification/service/CaseService.scala, app/uk/gov/hmrc/bindingtariffclassification/service/EventService.scala, conf/app.routes, test/unit/uk/gov/hmrc/bindingtariffclassification/controllers/CaseControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/controllers/EventControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepositorySpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/EventRepositorySpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/service/CaseServiceSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/service/EventServiceSpec.scala
Supporting PR for being able to delete only migrated cases
=> DIT-2521 | Delete specific events and cases

app/uk/gov/hmrc/bindingtariffclassification/crypto/Crypto.scala, test/it/uk/gov/hmrc/bindingtariffclassification/component/CaseSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/crypto/CryptoSpec.scala, test/util/CaseData.scala
@DavidGregory084 @gorkemunsal can you double check that I've chosen appropriate fields for encryption?
=> DIT-2534 | Fixed handling of misc and correspondence applications

app/uk/gov/hmrc/bindingtariffclassification/model/Application.scala, test/it/uk/gov/hmrc/bindingtariffclassification/component/CaseSpec.scala, test/util/CaseData.scala
To support https://github.com/hmrc/binding-tariff-data-transformation/pull/112
=> DIT-2575 | Updating liabilities application model

app/uk/gov/hmrc/bindingtariffclassification/common/Logging.scala, app/uk/gov/hmrc/bindingtariffclassification/connector/BankHolidaysConnector.scala, app/uk/gov/hmrc/bindingtariffclassification/controllers/CaseController.scala, app/uk/gov/hmrc/bindingtariffclassification/controllers/CommonController.scala, app/uk/gov/hmrc/bindingtariffclassification/migrations/AmendDateOfExtractMigrationJob.scala, app/uk/gov/hmrc/bindingtariffclassification/migrations/MigrationRunner.scala, app/uk/gov/hmrc/bindingtariffclassification/scheduler/ActiveDaysElapsedJob.scala, app/uk/gov/hmrc/bindingtariffclassification/scheduler/ReferredDaysElapsedJob.scala, app/uk/gov/hmrc/bindingtariffclassification/scheduler/Scheduler.scala, conf/application-json-logger.xml, conf/application.conf
Also see
- https://github.com/hmrc/app-config-staging/pull/7211
- https://github.com/hmrc/app-config-qa/pull/9961
- https://github.com/hmrc/app-config-production/pull/9671
=> DIT 2631 - Standardising logging config

app/uk/gov/hmrc/bindingtariffclassification/connector/FileStoreConnector.scala, app/uk/gov/hmrc/bindingtariffclassification/model/Paged.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/BaseMongoOperations.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/CaseKeywordMongoView.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepository.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/SearchMapper.scala, app/uk/gov/hmrc/bindingtariffclassification/scheduler/ActiveDaysElapsedJob.scala, app/uk/gov/hmrc/bindingtariffclassification/scheduler/ReferredDaysElapsedJob.scala, app/uk/gov/hmrc/bindingtariffclassification/service/KeywordService.scala, app/uk/gov/hmrc/bindingtariffclassification/service/ReportService.scala, build.sbt, conf/application.conf, test/unit/uk/gov/hmrc/bindingtariffclassification/repository/CaseKeywordMongoViewSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/service/ReportServiceTest.scala
=> DDCE-2069 - application fix for the one failing acceptance test

app/uk/gov/hmrc/bindingtariffclassification/model/Paged.scala, app/uk/gov/hmrc/bindingtariffclassification/model/Pagination.scala, app/uk/gov/hmrc/bindingtariffclassification/model/RejectReason.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/CaseRepository.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/MigrationLockRepository.scala, app/uk/gov/hmrc/bindingtariffclassification/repository/SearchMapper.scala, app/uk/gov/hmrc/bindingtariffclassification/scheduler/ActiveDaysElapsedJob.scala, app/uk/gov/hmrc/bindingtariffclassification/scheduler/StatusTimeline.scala, app/uk/gov/hmrc/bindingtariffclassification/service/UsersService.scala, build.sbt, project/AppDependencies.scala, project/plugins.sbt, run_all_tests.sh, test/unit/uk/gov/hmrc/bindingtariffclassification/metrics/HasMetricsSpec.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/model/CaseSearchTest.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/model/EventSearchTest.scala, test/unit/uk/gov/hmrc/bindingtariffclassification/model/UserSearchTest.scala
Upgrade from Scala 2.12 to 2.13
=> DDCE-3548: upgrade to Scala 2.13

app/uk/gov/hmrc/bindingtariffclassification/repository/BaseMongoOperations.scala, project/AppDependencies.scala, project/plugins.sbt
=> DDCE-6884 Com. mongodb .Mongo Command Exception
